added version check

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -25,13 +25,27 @@ jobs:
           pattern: ${{ needs.build.outputs.artifact-prefix }}-*
           merge-multiple: true
 
+      - name: Install dependencies
+        run: |
+          sudo snap install yq
+
       - name: Install snap package(s)
         run: |
           sudo snap install --dangerous charmed-etcd*.snap
 
       - name: Check etcd service status and run etcdctl and etcdutl
         run: |
-          sudo systemctl status snap.charmed-etcd.etcd.service | grep 'active (running)'
+          sudo systemctl status snap.charmed-etcd.daemon.service | grep 'active (running)'
+
+          expected_version="$(cat snap/snapcraft.yaml | yq .version)"
+
+          version="$(curl -L http://localhost:2379/version | yq -p=json .etcdserver)"
+
+          if [ "$expected_version" != "$version" ]; then
+            echo "Error: etcd Version is ${version}, expected {expected_version}"
+            exit 1
+          fi
+
           charmed-etcd.etcdctl version
           charmed-etcd.etcdutl version
 
@@ -43,4 +57,4 @@ jobs:
 
       - name: Run Performance checks
         run: |
-          charmed-etcd.etcdctl check perf
+          charmed-etcd.etcdctl check perf | grep 'PASS'
